FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential man-db sudo

ADD . /repo
WORKDIR /repo
RUN make -j8 install

RUN mkdir -p /deps
RUN ldd /usr/bin/nhance | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:20.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /usr/bin/nhance /usr/bin/nhance
ENV LD_LIBRARY_PATH=/deps
